import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Container';
import Col from 'react-bootstrap/Container';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NFT Factory - Generate a full collection of NFTs!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Row>
            <Col md="3"></Col>
            <Col md="9"></Col>
          </Row>
        </Container>
      </main>
    </div>
  );
}
